config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "project/maavens", to: "pages#maavens"
  get "project/ui_kit", to: "pages#ui_kit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/element.rb
class Element < ApplicationRecord
end

app/models/message.rb
class Message
	include ActiveModel::Model
  attr_accessor :name, :email, :body
  
  validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def default_url_options
	  { host: ENV["DOMAIN"] || "localhost:3000" }
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def maavens
  end

  def ui_kit
    @components = Element.where(component: true).order(:name)
    @layouts = Element.where(layout: true).order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
	<div class="header-container">
		<h1 class="text-4xl font-bold mb-4">Hi, I’m Jessie 👋</h1>
		<h2 class="text-2xl pr-lg pr-xlg">I am a 2-time founder and product manager transitioning into a formal software engineering role.</h2>
	</div>
	<div class="projects-container">
		<h4 class="text-accent text-md font-bold mb-5">Things I've built</h4>
		<%= link_to project_maavens_path do %>
			<div class="card-project">
				<h3 class="text-3xl font-bold mb-3">MAAVENS</h3>
				<p class="text-sm">Product recommendations from people you trust</p>
			</div>
		<% end %>
		<%= link_to project_ui_kit_path do %>
			<div class="card-project">
				<h3 class="text-3xl font-bold mb-3">UI Kit</h3>
				<p class="text-sm">Components and layouts for you to build from</p>
			</div>
		<% end %>
	</div>
</div>

app/views/pages/maavens.html.erb
<% content_for :meta_title, "Jessie Baxter | MAAVENS Project" %>
<% content_for :meta_description, "Product recommendations from people you trust" %>

<div class="block-image-overflow">
	<div class="container">
		<div class="header-container">
			<h1 class="text-4xl font-bold mb-4">MAAVENS</h1>
			<h2 class="text-2xl pr-lg pr-xlg">Product recommendations from people you trust</h2>
			<%= link_to "www.maavens.com", "https://www.maavens.com/", target: "_blank", class: "text-md text-brand" %>
			<div class="hero-image">
				<img src="https://res.cloudinary.com/dswcvx3gy/image/upload/v1655523324/maavens_banner.jpg" alt="">
			</div>
		</div>
		<div class="project-details-container pl-lg">
			<h3 class="text-3xl font-bold mb-3">Why</h3>
			<p class="text-sm-accent mb-3">"A maven is a trusted expert in a particular field, who seeks to pass timely and relevant knowledge on to others in the respective field." <%= link_to " - Wikipedia", "https://en.wikipedia.org/wiki/Maven", target: "_blank" %></p>
			<p class="text-sm mb-5">Friend recommendations matter to 70% of millennial consumers and those same consumers are increasingly looking for those opinions in the media [social] they consume. The problem is that the multi-flow of social content online means that a lot of those trusted opinions get lost in the noise. Maavens aims to collate those recommendations into a searchable and shoppable format.</p>
			<h3 class="text-3xl font-bold mb-3">How</h3>
			<p class="text-sm-accent mb-2">Leveraged: HTML, CSS, JavaScript, Ruby on Rails, PostgreSQL</p>
			<p class="text-sm mb-5">Built mobile-first Ruby on Rails application supporting authentication, authorization, filtering, search, manual and automated product matching and automated product availability/price monitoring.</p>
			<h3 class="text-3xl font-bold mb-3">What</h3>
			<p class="text-sm mb-2"><strong>Engagement: </strong>15k+ Pageviews/month</p>
			<p class="text-sm mb-5"><strong>Conversion: </strong>7.1%</p>
		</div>
	</div>
</div>

app/views/pages/ui_kit.html.erb
<% content_for :meta_title, "Jessie Baxter | UI Kit Project" %>
<% content_for :meta_description, "Components and layouts for you to build from" %>

<!-- Sidebar for md+ screens -->
<div id="ui-kit-nav">
  <div class="flex-shrink-0 px-3 pb-3 bg-white d-none d-md-block position-fixed" style="width: 280px;">
    <ul class="list-unstyled ps-0">
    	<li class="border-top my-3"></li>  
      	<%= render 'shared/ui_kit_nav' %>
      <li class="border-top my-3"></li>    
    </ul>
  </div>
<!-- Top nav for xs & sm screens -->
  <div class="navbar navbar-expand-md navbar-light navbar-ui d-md-none py-2 px-3">
    <div class="container-fluid">
      <div></div>
      <!-- Hamburger menu -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
        	<%= render 'shared/ui_kit_nav' %>
        </ul>
      </div>
    </div>
  </div>
</div>
<section class="main-content py-5" id="top">
  <div class="container">
    <!-- Components -->
    <% if @components.present? %>
      <h1 class="text-4xl font-bold mb-4">Components</h1>
      <p class="text-sm">Most of the components have a dependency on <%= link_to "Bootstrap (5.1)", "https://getbootstrap.com/", target: "_blank" %> & <%= link_to "Fontawesome", "https://origin.fontawesome.com/", target: "_blank" %>, so please make sure you have the libraries in your project.</p>
      <% @components.each do |component| %>
        <%= render 'shared/ui_kit_section', element: component %>
      <% end %>
    <% end %>
    <!-- Layouts -->
    <% if @layouts.present? %>
      <h1 class="text-4xl font-bold mt-5 mb-5">Layouts</h1>
      <% @layouts.each do |layout| %>
        <%= render 'shared/ui_kit_section', element: layout %>
      <% end %>
    <% end %>
    <!-- PLAYGROUND -->
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show mt-70" role="alert">
    <div class="content">
      <div class="line"></div>
      <i class="icon fas fa-check-circle"></i>
      <div class="details">
        <h5>Yay! 🎉</h5>
        <p><%= notice %></p>
      </div>
    </div>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="dismiss fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-warning alert alert-dismissible fade show mt-70" role="alert">
    <div class="content">
      <div class="line"></div>
      <i class="icon fas fa-exclamation-circle"></i>
      <div class="details">
        <h5>Oops! 😱</h5>
        <p><%= alert %></p>
      </div>
    </div>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="dismiss fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/jessiebbaxter" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/jessiebbaxter/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Current favorite emojis: 🤗 🙃
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-custom navbar-bg-trans fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <div class="">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-ghost btn-brand" data-bs-toggle="modal" data-bs-target="#contactModal">Say hi!</button>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="mx-3"></div>
        <h4 class="modal-title" id="contactModalLabel">🤗</h4>
        <button type="button" class="btn btn-x" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5 class="mb-3 font-bold">Email me at</h5>
        <p class="mb-4">jessie.baxter29@gmail.com</p>
        <h5 class="mb-3 font-bold">Or reach out on your preferred platform</h5>
        <%= link_to "LinkedIn", "https://www.linkedin.com/in/jessiebbaxter/", target: "_blank", class: "text-brand d-block pb-2" %>
        <%= link_to "Twitter", "https://twitter.com/jessiebbaxter", target: "_blank", class: "text-brand d-block pb-2" %>
        <%= link_to "Instagram", "https://www.instagram.com/jessiebbaxter/", target: "_blank", class: "text-brand d-block" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-exit" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ui_kit_nav.html.erb
<% if @components.present? %>
  <li class="mb-1">
    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#component-collapse" aria-expanded="true">
      Components
    </button>
    <div class="collapse show" id="component-collapse">
      <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
        <% @components.each do |component| %>
          <li><a href='#<%= component.name.parameterize %>' class="link-dark rounded ui-kit-element"><%= component.name.capitalize %></a></li>
        <% end %>
      </ul>
    </div>
  </li>
<% end %>
<% if @layouts.present? %>
  <li class="mb-1">
    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#layout-collapse" aria-expanded="false">
      Layouts
    </button>
    <div class="collapse" id="layout-collapse">
      <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
        <% @layouts.each do |layout| %>
          <li><a href='#<%= layout.name.parameterize %>' class="link-dark rounded ui-kit-element"><%= layout.name.capitalize %></a></li>
        <% end %>
      </ul>
    </div>
  </li>
<% end %>

app/views/shared/_ui_kit_section.html.erb
<section id='<%= element.name.parameterize %>'>
  <h2 class="text-2xl"><%= element.name.capitalize %></h2>
  <div class="element-preview">
    <%= element.html.html_safe %>
  </div>
  <div class="card-code">
    <div class="card-code-header">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <button class="nav-link active" id="nav-html-tab" data-bs-toggle="tab" data-bs-target='#<%= element.name.parameterize %>-html' type="button" role="tab" aria-controls="nav-html" aria-selected="true">HTML</button>
          <button class="nav-link" id="nav-css-tab" data-bs-toggle="tab" data-bs-target='#<%= element.name.parameterize %>-css' type="button" role="tab" aria-controls="nav-css" aria-selected="false">CSS</button>
        </div>
      </nav>
      <div class="card-code-body tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id='<%= element.name.parameterize %>-html' role="tabpanel" aria-labelledby="nav-html-tab">
          <pre>
            <code class="language-html">
<%= element.html %>
            </code>
          </pre>
        </div>
        <div class="tab-pane fade" id='<%= element.name.parameterize %>-css' role="tabpanel" aria-labelledby="nav-css-tab">
          <pre>
            <code class="language-css">
<%= element.css %>
            </code>
          </pre>
        </div>
      </div>
    </div>
  </div>
</section>